server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/servidores
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: servidores-bucket
