server:
  port: 8080

services:
  servidores-api:
    env_file:
      - .env
    environment:
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN:http://localhost:3000}

jwt:
  secret: ${JWT_SECRET:uma-chave-muito-segura-mesmo-aqui}
  access-token-expiration-ms: 300000      # 5 minutos
  refresh-token-expiration-ms: 604800000  # 7 dias

logging:
  level:
    org.springframework.security: DEBUG

spring:
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    repair-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/servidores
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: servidores-bucket
