server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/servidores
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: servidores-bucket
